name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    branches: [main] # Optional: run automatically when you push to main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Optional test step — skip it if you don't have tests yet
      - name: Run tests
        run: |
          if [ -f package.json ] && grep -q "\"test\":" package.json; then
            npm test || echo "⚠️ Tests failed or not defined — skipping"
          else
            echo "ℹ️ No tests found, skipping"
          fi

      - name: Build project (if applicable)
        run: npm run build --if-present

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js for publishing
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project (if applicable)
        run: npm run build --if-present

      - name: Publish package to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
